# Generated by Django 4.2.9 on 2024-02-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='classic', max_length=255),
            preserve_default=False,
        ),
    ]
