# Generated by Django 4.2.9 on 2024-02-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
