# Generated by Django 4.2.9 on 2024-05-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
