# Generated by Django 5.0.1 on 2024-03-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingcalc',
            options={'verbose_name_plural': 'ذرعات البنايات'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'المشاريع'},
        ),
        migrations.AlterModelOptions(
            name='companytype',
            options={'verbose_name_plural': 'انواع المشاريع'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name_plural': 'الفواتير'},
        ),
        migrations.AlterModelOptions(
            name='workercalc',
            options={'verbose_name_plural': 'ذرعات الخلفات'},
        ),
    ]
