# Generated by Django 4.2.9 on 2024-05-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0002_alter_buildingcalc_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuildingCalc',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='container',
        ),
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='container',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='container',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='container',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='withdraw_type',
        ),
        migrations.DeleteModel(
            name='WorkerCalc',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyType',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
        migrations.DeleteModel(
            name='Withdraw',
        ),
        migrations.DeleteModel(
            name='WithdrawType',
        ),
    ]
